kanta = float(input("syötä suorakulmion kanta: "))
korkeus = float(input("syötä suorakulmion korkeus: "))
print("suorakulmion pinta-ala: \nsuorakulmion piiri: ")
print ("piiri: " + str(kanta + kanta + korkeus + korkeus))
print ("pinta-ala: " + str(kanta * korkeus))